spring:
  application:
    name: twitchBot

name: dev-yml
enabled: true

socket:
  socket-url: wss://irc-ws.chat.twitch.tv:443

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:selfsigned.p12
    key-store-password: password
    key-alias: selfsigned
    enabled: true

twitch:
  user-auth: https://id.twitch.tv/oauth2/authorize
  client-id: <client-id>
  client-secret: <client-secret>
  redirect-uri: http://localhost:8080/oauth/redirect
  validate-uri: https://id.twitch.tv/oauth2/validate
  scope: chat%3Aedit+chat%3Aread
  oauth-uri: https://id.twitch.tv/oauth2/token
  bot-channel: <bot-channel-name>
